-- Copyright © 2020 Dennis Schulmeister-Zimolong
-- 
-- E-Mail: dhbw@windows3.de
-- Webseite: https://www.wpvs.de/
-- 
-- Dieser Quellcode ist lizenziert unter einer
-- Creative Commons Namensnennung 4.0 International Lizenz.

INSERT INTO SCORECARD(GAME_DATE_TIME, GOLF_COURSE) VALUES ('2020-02-15 12:00:00', 'Golfclub Rheinstetten');
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 1, 3, 3, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 2, 3, 4, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 3, 3, 3, 1);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 4, 3, 5, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 5, 3, 4, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 6, 3, 3, 2);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 7, 3, 5, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 8, 3, 5, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (1, 9, 3, 4, 1);

INSERT INTO SCORECARD(GAME_DATE_TIME, GOLF_COURSE) VALUES ('2020-02-10 17:45:00', 'Golfclub Rheinstetten');
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 1, 3, 3, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 2, 3, 3, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 3, 3, 4, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 4, 3, 3, 1);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 5, 3, 5, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 6, 3, 4, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 7, 3, 4, 1);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 8, 3, 4, 0);
INSERT INTO HOLE(SCORECARD_ID, HOLE_NUMBER, PAR, REGULAR_STROKES, PENALTY_STROKES) VALUES (2, 9, 3, 5, 0);