-- Copyright © 2020 Dennis Schulmeister-Zimolong
-- 
-- E-Mail: dhbw@windows3.de
-- Webseite: https://www.wpvs.de/
-- 
-- Dieser Quellcode ist lizenziert unter einer
-- Creative Commons Namensnennung 4.0 International Lizenz.

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('Star Trek: Der Film', 'Sci-Fi', 1979);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (1, 'Montag', '20:00:00', 5);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (1, 'Dienstag', '21:30:00', 5);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('The Blues Brothers', 'Comedy', 1980);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (2, 'Sonntag', '14:30:00', 2);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('Tron', 'Fantasy', 1982);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (3, 'Sonntag', '17:00:00', 2);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('War Games', 'Drama', 1983);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (4, 'Mittwoch', '16:00:00', 4);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (4, 'Donnerstag', '16:00:00', 4);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('Spaceballs', 'Comedy', 1987);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (5, 'Donnerstag', '20:00:00', 5);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (5, 'Samstag', '13:00:00', 1);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('Wall Street', 'Drama', 1987);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (6, 'Samstag', '16:30:00', 2);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('Moon', 'Sci-Fi', 2009);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (7, 'Freitag', '19:15:00', 2);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (7, 'Samstag', '15:30:00', 5);

INSERT INTO FILM (NAME, GENRE, JAHR) VALUES ('Der Marsianer – Rettet Mark Watney', 'Sci-Fi', 2015);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (8, 'Dienstag', '22:30:00', 2);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (8, 'Donnerstag', '22:00:00', 3);
INSERT INTO VORFUEHRUNG (FILM_ID, WOCHENTAG, UHRZEIT, SAALNR) VALUES (8, 'Sonntag', '11:15:00', 3);