-- Copyright © 2020 Dennis Schulmeister-Zimolong
-- 
-- E-Mail: dhbw@windows3.de
-- Webseite: https://www.wpvs.de/
-- 
-- Dieser Quellcode ist lizenziert unter einer
-- Creative Commons Namensnennung 4.0 International Lizenz.

INSERT INTO DEVICE_CLASS(NAME) VALUES ('Notebooks');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (1, 'Lenovo', 'Thinkpad E580', '2020-01-20');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (1, 'Lenovo', 'Thinkpad E680', '2020-01-22');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (1, 'Sony', 'Vayio', '2019-06-03');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (1, 'Acer', 'Primebook', '2019-11-14');

INSERT INTO DEVICE_CLASS(NAME) VALUES ('Smartphones');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (2, 'Jolla', 'Jolla C', '2019-11-14');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (2, 'Apple', 'iPhone 7', '2020-02-08');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (2, 'Samsung', 'Galaxy Phone', '2020-03-01');
INSERT INTO DEVICE(DEVICE_CLASS_ID, MANUFACTURER, MODEL, BUYING_DATE) VALUES (2, 'Planet Devices', 'Cosmo', '2019-12-01');
